modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/rhysdh540/f3-command/issues"

[[mods]]
modId = "f3"
version = "${version}"
displayName = "F3 Command"
logoFile = "icon.png"
authors = "rdh"
description = '''
F3 but it's a command
'''

[[dependencies.f3]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.f3]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "CLIENT"